### DISCUSSION TITLE
Adding coordinates to the geocodes location

### DISCUSSION THREAD

**Discussion by arjanhs** [Hyundai-Kia-Connect/kia_uvo#327] [Ideas]
Can the coordinates of the car be added to the geocodes location of the car so it would be visable on a map?

**Comment by jblaze03** [comment]
If you create a person in the people section then add the location tracker from this integration to the person you created you will see the location on the map if you click on the created person

**Comment by richy58729** [comment]
The coordinates are already in the data, even without enabling Geolocation.

That said, I have made something that comes close (and that doesn't need Geolocation, so you don't have to enable it to make this work) and gives you a link which shows your car's location on OpenStreetMap:

# Configuration

1. Go to [Settings &rarr; Devices \& Services &rarr; Integrations, devices, entities and helpers &rarr; Helpers](https://my.home-assistant.io/redirect/helpers/).
1. Make a new text helper and give it the name _OSM URL_.
1. Go [Settings &rarr; Automations \& Scenes &rarr; Scripts](https://my.home-assistant.io/redirect/scripts/).
1. Add a script, click on the hamburger menu at the top right, choose _Edit in YAML_, input the following code and save it:
``` yaml
alias: Make OSM url with car location
sequence:
  - service: input_text.set_value
    data:
      value: >-
        https://www.openstreetmap.org/search?query={{
        state_attr('binary_sensor.e_niro_data',
        'vehicle_data').vehicleLocation.coord.lat }}%2C+{{
        state_attr('binary_sensor.e_niro_data',
        'vehicle_data').vehicleLocation.coord.lon }}#map={{
        states('input_number.osm_zoom_level') | int }}/{{
        state_attr('binary_sensor.e_niro_data',
        'vehicle_data').vehicleLocation.coord.lat }}/{{
        state_attr('binary_sensor.e_niro_data',
        'vehicle_data').vehicleLocation.coord.lon }}
    target:
      entity_id: input_text.osm_url
mode: single
```
I'm not 100% sure if the name of the device is the same in your instance of HA (mine is _e\_niro_). If it is something different, change it in the above code.
5. Edit your dashboard, add a card, choose _Manual_, input the following and save it:
``` yaml
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_number.osm_zoom_level
        name: OSM zoom level
    title: Show car location on map
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: script.make_osm_url_with_car_location
      data: {}
      target: {}
    name: Make OSM URL
    hold_action:
      action: none
    icon: mdi:map-marker
  - type: entity
    entity: input_text.osm_url
    name: OSM URL

```

# How to use

This is assuming you're using a smartphone or tablet.

1. Set the _OSM zoom level_ (0 is zoomed all the way out and 19 is zoomed all the way in).
1. Tap on _Make OSM URL_.
1. Tap on _OSM URL_. This should at least work on an Android phone (iPhone/iPad I'm not sure), on the info tab, tap and hold on the URL. You should get a context menu with the possibility to open the URL in a web browser. You should see the location of your car on the OpenStreetMap web site.
