### DISCUSSION TITLE
How to read out attributes of sensor.ev6_daily_driving_stats

### DISCUSSION THREAD

**Discussion by MichT368** [Hyundai-Kia-Connect/kia_uvo#781] [Q&A] [answered]
I recently discovered, that  sensor.ev6_daily_driving_stats contains a lot of statistic information regarding energy consumption on a daily base, stored in attributes.
If found, that I can read out those information by using a lovelace markdown card, using this template:

<pre>
{% for date, data in states['sensor.ev6_daily_driving_stats'].attributes.items() %}
  <div>
    {% if date is defined and date is string and date | regex_match('^\\d{4}-\\d{2}-\\d{2}$') %}
      {{ date }}
      {% if data is mapping %}
          Total Consumed: {{ data.total_consumed }}
          Engine Consumption: {{ data.engine_consumption }}
          Climate Consumption: {{ data.climate_consumption }}
         <\!-- Add more of the attributes here -->
      {% endif %}
    {% endif %}
  </div>
{% endfor %}

</pre>

Has anybody found a solution to use those attributes in diagrams inside HA, instead of scrolling in lists?
Some support would be very much appreciated.
Thank you.
Michael

**Comment by mztiq** [comment]
I'm very interested in this too since the attributes of this sensor hold so much information.

**Comment by MichT368** [comment]
I have destillated a list of dates and the Attribute part "total_consumed" this way, which is basically the same as before:

```
{% for date, data in states['sensor.ev6_daily_driving_stats'].attributes.items() %}
    {% if date is defined and date is string and date | regex_match('^\\d{4}-\\d{2}-\\d{2}$') %}
      {{ date }}
      {% if data is mapping %}
          Total Consumed: {{ data.total_consumed }}
      {% endif %}
    {% endif %}
{% endfor %}
``` 

I have worked with ChatGPT now for about an hour to get this data into apexcharts-card (https://github.com/RomRider/apexcharts-card), but no luck yet.

Michael

**Comment by MichT368** [comment, marked as answer]
Finally figured out how to get data out for a apex-chart card (https://github.com/RomRider/apexcharts-card)

This card shows all data of 'total_consumed' in the attributes of sensor.ev6_daily_driving_stats in lovelace apexcharts-card:

```
type: custom:apexcharts-card
apex_config:
  chart:
    height: 500px
graph_span: 28d
span:
  end: day
show:
  last_updated: true
header:
  show: true
  show_states: false
  colorize_states: true
  title: EV6 Gesamtverbrauch (Wh)
series:
  - entity: sensor.ev6_daily_driving_stats
    type: column
    data_generator: |
      return Object.entries(entity.attributes).map(([date, stats]) => {
        return { x: new Date(date), y: stats.total_consumed };
      });
    unit: Wh
```
Hope this helps someone.

Michael

**Reply by mztiq** [reply]
This is great! Thanks for sharing, much appreciated and works perfectly fine for my IONIQ 5 too.

**Reply by MichT368** [reply]
War mir ein Vergnügen!

**Reply by briadelour** [reply]
Thanks!  Works great with my Ioniq 6!

**Reply by jdelamater99** [reply]
This was a good starting place, but the card wasn't populating with data for me.

In order to get it working for me, I had to redo the data_generator portion of the code. I also converted to kWh.

```
  - entity: sensor.2022_ioniq_5_daily_driving_stats
    type: line
    data_generator: |
      return Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date))
        .map(([date, stats]) => {
          return { x: new Date(date), y: stats.total_consumed/1000 };
        });
    unit: kWh
```

**Reply by MichT368** [reply]
Thank you for this approach. It leads me to this card here:
```
type: custom:apexcharts-card
graph_span: 12d
apex_config:
  chart:
    height: 375px
span:
  end: day
show:
  last_updated: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: EV6 Verbrauch (Ø)
series:
  - entity: sensor.ev6_daily_driving_stats
    type: column
    data_generator: |
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      return entries.map(([date, stats]) => {
        return { x: new Date(date), y: stats.total_consumed / 1000 };
      });
    unit: kWh
    show:
      in_header: false
      in_chart: true
      in_legend: true
  - entity: sensor.ev6_daily_driving_stats
    type: line
    transform: >
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      let sum = entries.reduce((acc, [_, stats]) => acc + stats.total_consumed,
      0);

      return sum / entries.length / 1000;
    unit: kWh/d Average
    show:
      in_chart: false
      in_legend: false
      in_header: true
    color: "#ff9800"

```
Otherwise you get a "N/A" in the card header.
It's a smart solution, if you get the average consumption of the car instead:
Thank you!

**Comment by badnbusy** [comment]
Is there any way to use this data to show a chart with how much percentage of the battery was used each day? For example, if the batter was 64kWh, based off the daily kWh consumption, can it show a percentage of battery taken each day?

**Reply by bavala3010** [reply]
> Is there any way to use this data to show a chart with how much percentage of the battery was used each day? For example, if the batter was 64kWh, based off the daily kWh consumption, can it show a percentage of battery taken each day?

Here is the code for the % used.

```
type: custom:apexcharts-card
graph_span: 14d
update_interval: 15m
apex_config:
  grid:
    show: false
  dataLabels:
    offsetY: -10
    background:
      enabled: false
    style:
      colors:
        - var(--primary-text-color)
  plotOptions:
    bar:
      columnWidth: 60%
      borderRadius: 4
  xaxis:
    axisTicks:
      show: false
    axisBorder:
      show: false
    labels:
      offsetY: -5
      datetimeFormatter:
        day: dd
  yaxis:
    decimals: 0
    crosshairs:
      show: true
    axisTicks:
      show: true
    tickAmount: 5
    labels:
      show: true
      maxwidth: 4
  tooltip:
    enabled: false
  legend:
    show: true
    position: top
    horizontalAlign: center
span:
  end: day
show:
  last_updated: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: EV6 Battery Usage
series:
  - entity: sensor.ev6_daily_driving_stats
    type: column
    data_generator: |
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      return entries.map(([date, stats]) => {
        let consumed_kWh = stats.total_consumed / 1000;  // Convert Wh to kWh
        let battery_percentage = (consumed_kWh / 64) * 100;  // Calculate percentage of 64 kWh
        return { x: new Date(date), y: battery_percentage };
      });
    unit: '%'
    show:
      in_chart: true
      in_header: false
      in_legend: true
      datalabels: true
    color: "#8d37ff"
    name: Battery Usage
  - entity: sensor.ev6_daily_driving_stats
    type: line
    transform: |
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      let sum = entries.reduce((acc, [_, stats]) => acc + stats.total_consumed, 0);
      let average_kWh = (sum / entries.length) / 1000;  // Calculate average in kWh
      let average_percentage = (average_kWh / 64) * 100;  // Calculate average percentage
      return average_percentage;
    unit: '%/day'
    show:
      in_chart: false
      in_header: true
    color: "#8d37ff"
    name: Average Usage
```

**Comment by bavala3010** [comment]
Based on the above code (thanks !) I made 2 charts: 1 for daily energy consumption and another for the daily km.

Independently, the graphs are displaying correctly, but I am not able to combine them into 1 graph with 2 diffferent vertical axis. Anyone?
Any other optimisatons are welcome.

```
type: custom:apexcharts-card
graph_span: 14d
update_interval: 15m
apex_config:
  grid:
    show: false
  dataLabels:
    offsetY: -10
    background:
      enabled: false
    style:
      colors:
        - var(--primary-text-color)
  plotOptions:
    bar:
      columnWidth: 60%
      borderRadius: 4
  xaxis:
    axisTicks:
      show: false
    axisBorder:
      show: false
    labels:
      offsetY: -5
      datetimeFormatter:
        day: dd
  yaxis:
    decimals: 0
    crosshairs:
      show: true
    axisTicks:
      show: true
    tickAmount: 5
    labels:
      show: true
      maxwidth: 4
  tooltip:
    enabled: false
  legend:
    show: true
    position: top
    horizontalAlign: center
span:
  end: day
show:
  last_updated: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: EV6 Energy
series:
  - entity: sensor.ev6_daily_driving_stats
    type: column
    data_generator: |
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      return entries.map(([date, stats]) => {
        return { x: new Date(date), y: stats.total_consumed / 1000 };
      });
    unit: kWh
    show:
      in_chart: true
      in_header: false
      in_legend: true
      datalabels: true
    color: "#8d37ff"
  - entity: sensor.ev6_daily_driving_stats
    type: line
    transform: >
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      let sum = entries.reduce((acc, [_, stats]) => acc + stats.total_consumed,
      0);

      return sum / entries.length / 1000;
    unit: kWh/day
    show:
      in_chart: false
      in_header: true
    color: "#8d37ff"
    name: Average
```

```
type: custom:apexcharts-card
graph_span: 14d
apex_config:
  grid:
    show: false
  dataLabels:
    offsetY: -10
    background:
      enabled: false
    style:
      colors:
        - var(--primary-text-color)
  plotOptions:
    bar:
      columnWidth: 60%
      borderRadius: 4
  xaxis:
    axisTicks:
      show: false
    axisBorder:
      show: false
    labels:
      offsetY: -5
      datetimeFormatter:
        day: dd
  yaxis:
    decimals: 0
    crosshairs:
      show: true
    axisTicks:
      show: true
    tickAmount: 5
    labels:
      show: true
      maxwidth: 4
  tooltip:
    enabled: false
  legend:
    show: true
    position: top
    horizontalAlign: center
span:
  end: day
show:
  last_updated: true
header:
  standard_format: false
  show: true
  show_states: true
  colorize_states: true
  title: EV6 Kilometers
series:
  - entity: sensor.ev6_daily_driving_stats
    type: column
    data_generator: |
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      return entries.map(([date, stats]) => {
        return { x: new Date(date), y: stats.distance };
      });
    unit: km
    show:
      in_header: false
      in_chart: true
      in_legend: true
      datalabels: true
    color: teal
    name: Kilometers
  - entity: sensor.ev6_daily_driving_stats
    type: line
    transform: |
      let entries = Object.entries(entity.attributes)
        .filter(([date, stats]) => !['unit_of_measurement', 'friendly_name'].includes(date));
      let sum = entries.reduce((acc, [_, stats]) => acc + stats.distance, 0);
      return sum / entries.length / 1000;
    unit: km/day
    show:
      in_chart: false
      in_legend: true
      in_header: true
    color: teal
    name: Average
```
