### ISSUE TITLE
Sensor for the Guess-o-Meter estimated range on a 100% EV Battery

### ISSUE THREAD

**Issue by henrikbjorn** [Hyundai-Kia-Connect/kia_uvo#241]
Would be great to see the Guess-o-Meter for a full charge and thus be able to graf it.

This is interesting as the driving style will influence the GoM

**Comment by fuatakgun** [comment]
Was not able to understand, can you make it clear?

**Comment by henrikbjorn** [comment]
When you have an EV. The car "guesses" the distance left before the battery is empty. This is called a "Guess-o-Meter". This distance will change over time as it looks at how the car is driven and how battery is used.

So when you get the car it might say "480km" but after a month of driving it might be "400km" for a full charge.

I would love to be able to graph that data.

Also if the API returns it, the average consumption over 100km or how many km you can drive for 1 kw

I think it is this data from the api

``` yml
targetSOClist:
          - targetSOClevel: 100
            dte:
              rangeByFuel:
                evModeRange:
                  value: 404
                  unit: 1
                totalAvailableRange:
                  value: 404
                  unit: 1
              type: 2
            plugType: 1
          - targetSOClevel: 100
            dte:
              rangeByFuel:
                evModeRange:
                  value: 404
                  unit: 1
                totalAvailableRange:
                  value: 404
                  unit: 1
              type: 2
            plugType: 0
```

**Comment by fuatakgun** [comment]
Got it, this is about, charge my car up to 100% for DC or AC, and you will get 404km with 100% (independent of ac dc).

Not everyone sets up to charge up to 100%, on the other hand, you are interested with `goes 404km with target charge level`.

Is that correct?

**Comment by henrikbjorn** [comment]
I would always be interested in the 100% level, never mind the max charge level set.

DC/AC is just the type of charging. How fast the charge is.

**Comment by henrikbjorn** [comment]
Could also be interesting for gasoline cars. I assume they might expose other kind of range numbers that is also dependent on driving style.

**Comment by henrikbjorn** [comment]
There is also `evStatus.drvDistance` with some unclear named keys that might contain the correct data.

**Comment by fuatakgun** [comment]
Evstatus.drvdistance exposed remaining distance to consume the whole battery and there is a corresponding sensor for ic cars too. But it is not telling you the range for 100% battery level, you can formulate it though.

**Comment by henrikbjorn** [comment]
My mistake `evStatus.remainTime2` 

``` yml
      remainTime2:
        etc1:
          value: 58
          unit: 1
        etc2:
          value: 1240
          unit: 1
        etc3:
          value: 310
          unit: 1
        atc:
          value: 390
          unit: 1
```

Not sure what the atc etc names are.
