### ISSUE TITLE
Failed to call service number/set_value Duplicate request - Duplicate request

### ISSUE THREAD

**Issue by dc911x** [Hyundai-Kia-Connect/kia_uvo#498]
**Region and Brand of car**
EU - Ioniq 5

**Version of the integration**
Version 2.048

**Describe the bug**

When using the slider for the 2nd time after first sliding AC or DC in my lovelace dashboard I'm getting the error:
`Failed to call service number/set_value Duplicate request - Duplicate request`

example both AC and DC are set to 100% and I want to change them back to 80%

edit: After testing a bit the charging levels were set but it required multiple attempts and the slider is stuck many times:
![afbeelding](https://user-images.githubusercontent.com/49455017/207955617-78f42b16-c492-4545-a703-3bb0f006b4da.png)

**Debug logs if an error occurred**

```
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 544, in _get_forced_vehicle_state_check_response_for_errors(response)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 71, in _check_response_for_errorsraise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DuplicateRequestError: Duplicate request - Duplicate request
```

**To Reproduce**

Slide the AC and then DC charge limit slider without waiting a bit (or vice versa)

**Expected behavior**

Setting the sliders and after a delay set the charge levels, atm it seems it wants to set the charge right away causing the 2nd slider to error out.

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/49455017/207950086-bc7d906b-e821-4aa0-8921-56d20b538254.png)
![afbeelding](https://user-images.githubusercontent.com/49455017/207950747-e48af409-3f94-4454-aa59-1a2bb7d2bc53.png)
**Additional context**

This is all extra context not sure how valuable this will be:

A while back I made my own sliders to set the charging limits, I should check GitHub more then I would have seen you guys did it better with no button, extra automation and script needed like in my case.

I made 2 helpers in home assistant

```
input_number.ioniq5_ac_limit
input_number.ioniq5_dc_limit
```

Then made a script that sets sends the charging limit to the car, since trying to integrate this in the lovelace card didn't work...

```
alias: Set Charging Limits
sequence:
  - service: kia_uvo.set_charge_limits
    data:
      device_id: xxx
      dc_limit: "{{ states('input_number.ioniq5_dc_limit') | int(0) }}"
      ac_limit: "{{ states('input_number.ioniq5_ac_limit') | int(0) }}"
mode: single
icon: mdi:home-lightning-bolt-outline
```
note: script still works, I just needed to add the device_id since now we have multi vehicle support.

But now my sliders were out of sync if I changed the charging limit using the bluelink app or the car's build-in settings so I also made this automation:

```
alias: "[Ioniq 5] Update AC/DC target capacity of charge"
description: >-
  Updates the (helper) slider so the dashboard is always in sync even when I
  change the target capacity of charge in the car itself or the bluelink app.
trigger:
  - platform: state
    entity_id:
      - sensor.ioniq_5_target_capacity_of_charge_dc
      - sensor.ioniq_5_target_capacity_of_charge_ac
condition: []
action:
  - service: input_number.set_value
    data:
      value: "{{ (states('sensor.ioniq_5_target_capacity_of_charge_ac') | int) }}"
    target:
      entity_id: input_number.ioniq5_ac_limit
  - service: input_number.set_value
    data:
      value: "{{ (states('sensor.ioniq_5_target_capacity_of_charge_dc') | int) }}"
    target:
      entity_id: input_number.ioniq5_dc_limit
mode: single
```

Both `sensor.ioniq_5_target_capacity_of_charge_dc` or `sensor.ioniq_5_target_capacity_of_charge_ac` don't exist any more so useless automation...

--------------------

For those curious about the "Consumption" in the card, I should update it using the new "sensor.ioniq_5_monthly_energy_consumption" because I think my formule is wrong somewhere anyway:

```
  - platform: template
    sensors: 
      ioniq_5_battery_capacity:
        value_template: "72.6"
        unit_of_measurement: "kWh"
      ev_mileage_since_last_charge:
        value_template: "{{ states('sensor.ioniq_5_odometer') | int(0) - states('input_number.ev_mileage_since_last_charge_base') | int }}"
      ioniq_5_battery_capacity_remaining:
        value_template: "{{ ((states('sensor.ioniq_5_battery_capacity') | float * states('sensor.ioniq_5_ev_battery_level') | float ) / 100) | round(1) }}"
        unit_of_measurement: "kWh"
      ev_comsumption:
        value_template: "{{ (states('sensor.ev_mileage_since_last_charge') | float / ((states('sensor.ioniq_5_battery_capacity') | float - states('sensor.ioniq_5_battery_capacity_remaining') | float ))) | round(1) }}"
        unit_of_measurement: "km/kWh"
```
For this I use 2 input helpers:

```
input_number.ev_mileage_since_last_charge_base
ev_total_mileage_since_last_charge
```
and this automation:

```
alias: "[Ioniq 5] Update EV Mileage Stats"
description: Updates mileage stats after EV charger is connected
trigger:
  - platform: state
    entity_id: binary_sensor.ioniq_5_plugged_in
    from: "off"
    to: "on"
condition: []
action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.ev_total_mileage_since_last_charge
      value: "{{states('sensor.ev_mileage_since_last_charge') | float }}"
  - service: input_number.set_value
    data_template:
      entity_id: input_number.ev_mileage_since_last_charge_base
      value: "{{states('sensor.ioniq_5_odometer') | float }}"
mode: single
```

And maybe this can help some others too, below are sensors I needed to change to make my dashboard card work again:

`binary_sensor.ioniq_5_plugged_in` TO `binary_sensor.ioniq_5_ev_battery_plug`
`binary_sensor.ioniq_5_charging` TO `binary_sensor.ioniq_5_ev_battery_charge`
`sensor.ioniq_5_range_by_ev `TO `sensor.ioniq_5_ev_range`
`sensor.ioniq_5_last_update` TO `sensor.ioniq_5_last_updated_at`
`sensor.ioniq_5_ev_battery` TO `ensor.ioniq_5_ev_battery_level`
