### ISSUE TITLE
Kia e-Niro Climate not fully funktionable

### ISSUE THREAD

**Issue by rotknecht** [Hyundai-Kia-Connect/kia_uvo#975]
I have a Kia e-Niro (2020, EU) and can also start the air conditioning with it. Unfortunately, the steering wheel heating, defrosting and rear window heating are not switched on, even though they are selected.

I can trigger this without any problem in the UVO app.

Use this automation:

```
alias: "Stromer: Klimaanlage starten"
description: ""
triggers:
  - trigger: time
    at: "07:30:00"
conditions:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
actions:
  - action: kia_uvo.start_climate
    data:
      duration: 10
      climate: true
      temperature: 21
      defrost: true
      heating: "4"
      device_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mode: single
```

What can i do?

**Comment by joseapdmota** [comment]
> No clue if this will work for you but give it a try, this worked on my 2020 Hyundai Kona, change heating: "4" to heating: "1" instead. Then ignore what the UI says.

That did the trick for the steering wheel, but for some reason the seats are not warming up. Any tips here?

This is my yaml:
```
alias: Heat Kona
description: Morning Heating of Kona
triggers:
  - at: "08:00:00"
    trigger: time
conditions:
  - condition: numeric_state
    entity_id: sensor.temperature
    below: 10
actions:
  - data:
      climate: true
      temperature: 24
      defrost: true
      heating: "1"
      device_id: xxxxxxxxxxxxxxxxxxxxxxx
      flseat: "7"
      duration: 10
      frseat: "7"
    action: kia_uvo.start_climate
mode: single
```

Thanks.
